export const SET_PRODUCT_LIST="SET_PRODUCT_LIST"
export const PRODUCT_LIST="PRODUCT_LIST"
export const SEARCH_PRODUCT="SEARCH_PRODUCT"
export const BOOK = "BOOK"
export const  REMOVE = "REMOVE"
export const SUBMIT = "SUBMIT"
export const DELETE_PRODUCT ="DELETE_PRODUCT"
export const EDIT_PRODUCT = "EDIT_PRODUCT"