import { Inter } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.css';

const inter = Inter({ subsets: ["latin"] });
import Navbar from "../Navbar/page"
import Footer from "../Footer/page"
import StoreProvider from "@/Redux/storeProvider";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
{/* <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css"></link> */}
      <body className={inter.className}>
      {/* <script src="https://kit.fontawesome.com/9ce934e231.js" crossorigin="anonymous"></script> */}
        <StoreProvider>
        <Navbar/>
        {children}
        <Footer/>
        </StoreProvider>
        
        </body>
    </html>
  );
}
